import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Admin Modules
  {
    path: '/admin/dashboard/main',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [
     
    ],
    
  }
  ,
  ///admin/employees/employee-profile : profile
  {
    path: '/admin/employees/allEmployees',
    title: 'MENUITEMS.EMPLOYEES.TEXT',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin' , 'CompanyAdmin'],
    submenu: []
  },
  {
    path: '/admin/clients/all-clients',
    title: 'MENUITEMS.CLIENTS.TEXT',
    iconType: 'feather',
    icon: 'user-check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SystemAdmin'],
    submenu: [  ],
  }
  
  , {
    path: '/admin/clinics-list',
    title: 'MENUITEMS.CLINICS.TEXT',
    iconType: 'feather',  
     icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SystemAdmin' ],
    submenu: [],
  },
  
  {
    path: '/admin/all-services',
    title: 'MENUITEMS.SERVICES.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: '',          
    groupTitle: false,  
    badge: '',          
    badgeClass: '',     
    role: [ 'CompanyAdmin'],    
    submenu: [],        
  },
  {
    path: '/admin/appointments-list',
    title: 'MENUITEMS.APPOINTMENTS.TEXT',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu:[]
  },
  {
    path: '/admin/service-staff-list',
    title: 'MENUITEMS.PROJECTS.TEXT',
    iconType: 'feather',
    icon: 'link',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [],
  }
  
,


  
  {
    path: '',
    title: 'MENUITEMS.ACCOUNTS.TEXT',
    iconType: 'feather',
    icon: 'book-open',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin','Bookkeeper'],
    submenu: [
      {
        path: '/admin/accounts/all-payment',
        title: 'MENUITEMS.ACCOUNTS.LIST.ALL-PAYMENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/accounts/add-payment',
        title: 'MENUITEMS.ACCOUNTS.LIST.ADD-PAYMENT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/accounts/invoice',
        title: 'MENUITEMS.ACCOUNTS.LIST.INVOICE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin','Bookkeeper'],
    submenu: [
      {
        path: '/admin/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/payroll/payslip',
        title: 'MENUITEMS.PAYROLL.LIST.PAYSLIP',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },



  
  // Employee Modules
  {
    path: '/employee/dashboard',
    title: 'MENUITEMS.EMPLOYEE.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/attendance',
    title: 'MENUITEMS.EMPLOYEE.ATTENDANCE',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myleaves',
    title: 'MENUITEMS.EMPLOYEE.MY-LEAVES',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myteam',
    title: 'MENUITEMS.EMPLOYEE.MYTEAM',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myprojects',
    title: 'MENUITEMS.EMPLOYEE.MYPROJECTS',
    iconType: 'feather',
    icon: 'database',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/mytasks',
    title: 'MENUITEMS.EMPLOYEE.MYTASKS',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/settings',
    title: 'MENUITEMS.EMPLOYEE.SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/chat',
    title: 'MENUITEMS.EMPLOYEE.CHAT',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  // Client Modules
  {
    path: '/client/dashboard',
    title: 'MENUITEMS.CLIENT.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.CLIENT.APPOINTMENTS.TEXT', // en : src\assets\i18n\en.json 
    iconType: 'feather',
    icon: 'calendar',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [
      {
        path: '/client/appointment/booking',
        title:  'MENUITEMS.CLIENT.APPOINTMENTS.LIST.BOOK_APPOINTMENT',
        iconType: 'feather',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Client'],
        submenu: [],
      },
    ],
  },

  {
    path: '',
    title: 'medical record ',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [
      {
        path: '/client/projects/myProjects',
        title: 'Consultation',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/client/projects/projectDetails',
        title: 'MENUITEMS.CLIENT.PROJECTS.LIST.PROJECT-DETAILS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  


  {
    path: 'calendar',
    title: 'Calendar',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin', 'Client'],
    submenu: [],
  },
  {
    path: '/client/chat',
    title: 'MENUITEMS.CLIENT.CHAT',
    iconType: 'feather',
    icon: 'message-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },
  {
    path: '/client/settings',
    title: 'MENUITEMS.CLIENT.SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },
//doctor
{
  path: '/doctor/consultation',
  title: 'consultation',
  iconType: 'feather',
  icon: 'activity',
  class: '',
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: [ 'CompanyAdmin'],
  submenu: [],
},
  // Common Modules

  {
    path: '',
    title: 'Apps',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin', 'Employee'],
    submenu: [],
  },
  {
    path: '',
    title: 'Widgets',
    iconType: 'feather',
    icon: 'gift',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [
      {
        path: '/widget/chart-widget',
        title: 'Chart Widget',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/widget/data-widget',
        title: 'Data Widget',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Components',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [],
  },
  {
    path: '',
    title: 'User Interface (UI)',
    iconType: 'feather',
    icon: 'copy',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [
      {
        path: '/ui/alerts',
        title: 'Alerts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/badges',
        title: 'Badges',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/chips',
        title: 'Chips',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/modal',
        title: 'Modal',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/buttons',
        title: 'Buttons',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/expansion-panel',
        title: 'Expansion Panel',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/bottom-sheet',
        title: 'Bottom Sheet',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/dialogs',
        title: 'Dialogs',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/cards',
        title: 'Cards',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/labels',
        title: 'Labels',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/list-group',
        title: 'List Group',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/snackbar',
        title: 'Snackbar',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/preloaders',
        title: 'Preloaders',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/progressbars',
        title: 'Progress Bars',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/tabs',
        title: 'Tabs',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/typography',
        title: 'Typography',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/ui/helper-classes',
        title: 'Helper Classes',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Forms',
    iconType: 'feather',
    icon: 'layout',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [
      
      {
        path: '/forms/advance-controls',
        title: 'Advanced Controls',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/forms/form-example',
        title: 'Form Examples',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/forms/form-validation',
        title: 'Form Validation',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
   
    ],
  },
  
  {
    path: '',
    title: 'Charts',
    iconType: 'feather',
    icon: 'pie-chart',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '7',
    badgeClass: 'badge bg-green sidebar-badge float-end',
    role: [ 'CompanyAdmin'],
    submenu: [
      {
        path: '/charts/echart',
        title: 'Echart',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/charts/apex',
        title: 'Apex',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/charts/chartjs',
        title: 'ChartJS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/charts/ngx-charts',
        title: 'Ngx-Charts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
 
    ],
  },
  
 
  {
    path: '',
    title: 'Authentication',
    iconType: 'feather',
    icon: 'user-check',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [
      {
        path: '/authentication/signin',
        title: 'Sign In',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
 
      {
        path: '/authentication/forgot-password',
        title: 'Forgot Password',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/authentication/locked',
        title: 'Locked',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/authentication/page404',
        title: '404 - Not Found',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/authentication/page500',
        title: '500 - Server Error',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Extra Pages',
    iconType: 'feather',
    icon: 'anchor',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [ 'CompanyAdmin'],
    submenu: [
      {
        path: '/extra-pages/profile',
        title: 'Profile',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/extra-pages/pricing',
        title: 'Pricing',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/extra-pages/invoice',
        title: 'Invoice',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
   
      {
        path: '/extra-pages/blank',
        title: 'Blank Page',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

];
